DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE url_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url_id BIGINT NOT NULL,
    status_code INT NOT NULL,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT pk_url_checks PRIMARY KEY (id),
    CONSTRAINT fk_url_checks_url_id FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE
);